version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=socket-db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M